Shadow/Controllers/ProjectManagerController.cs
using Microsoft.AspNet.Identity;
using Shadow.BL;
using Shadow.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace Shadow.Controllers
{
    [Authorize(Roles ="project manager")]
    public class ProjectManagerController : Controller
    {
        ProjectManagerBusinessLayer ProjectManagerBusinessLayer = new ProjectManagerBusinessLayer();
        // GET: ProjectManager
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateAProject()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateAProject(string projectName)
        {
            var result = ProjectManagerBusinessLayer.AddANewProject(User.Identity.GetUserId(), projectName);
            if (result)
                return View();
            else
                return RedirectToAction("Index");
        }

        public ActionResult EditProject(int projectId)
        {
            var project = ProjectManagerBusinessLayer.GetProject(projectId);
            return View(project);
        }
        [HttpPost]
        public ActionResult EditProject(int projectId, Project project)
        {
            var result = ProjectManagerBusinessLayer.EditProject(User.Identity.GetUserId(), project);

            if (result)
                return View(project);
            else
                return RedirectToAction("Index");
        }

        public ActionResult AllProjectsByUser()
        {
            var projects = ProjectManagerBusinessLayer.GetAllofMyProjects(User.Identity.GetUserId());
            return View(projects);
        }

        public ActionResult AllProjects()
        {
            var projects = ProjectManagerBusinessLayer.AllProject(User.Identity.GetUserId());
            return View(projects);
        }

        public ActionResult AssignToProject()
        {
            ViewBag.UserList = ProjectManagerBusinessLayer.GetAllUsers();
            ViewBag.ProjectList = ProjectManagerBusinessLayer.AllProject(User.Identity.GetUserId());
            return View();
        }

        [HttpPost]
        public ActionResult AssignToProject(string userId, int projectId)
        {
            var result = ProjectManagerBusinessLayer.AssignUserToAProject(User.Identity.GetUserId(), userId, projectId);

            ViewBag.UserList = ProjectManagerBusinessLayer.GetAllUsers();
            ViewBag.ProjectList = ProjectManagerBusinessLayer.AllProject(User.Identity.GetUserId());

            if (result)
                return View();
            else
                return RedirectToAction("Index");
        }

        public ActionResult UnAssignFromProject()
        {
            ViewBag.UserList = ProjectManagerBusinessLayer.GetAllUsers();
            ViewBag.ProjectList = ProjectManagerBusinessLayer.AllProject(User.Identity.GetUserId());
            return View();
        }

        [HttpPost]
        public ActionResult UnAssignFromProject(string userId, int projectId)
        {
            var result = ProjectManagerBusinessLayer.UnAssignUserFromProject(User.Identity.GetUserId(), userId, projectId);

            ViewBag.UserList = ProjectManagerBusinessLayer.GetAllUsers();
            ViewBag.ProjectList = ProjectManagerBusinessLayer.AllProject(User.Identity.GetUserId());

            if (result)
                return View();
            else
                return RedirectToAction("Index");
        }

        public ActionResult GetAllTickets(string sortOrder,string currentFilter, string searchString, int? page)
        {
            List<Ticket> AllTickets;
            ViewBag.CurrentSort = sortOrder;

            if (searchString != null)
            {
                page = 1;
            } else
            {
                searchString = currentFilter;
            }
            switch (sortOrder)
            {
                case "OrderByAscending":
                    AllTickets = ProjectManagerBusinessLayer.GetAllTickets(User.Identity.GetUserId()).OrderBy(a => a.Title).ToList();
                    break;
                case "OrderByDescending":
                    AllTickets = ProjectManagerBusinessLayer.GetAllTickets(User.Identity.GetUserId()).OrderByDescending(d => d.Title).ToList();
                    break;
                default:
                    AllTickets = ProjectManagerBusinessLayer.GetAllTickets(User.Identity.GetUserId());
                    break;
            }

            if (!string.IsNullOrEmpty(searchString))
            {
                AllTickets = AllTickets.Where(s => s.Title.Contains(searchString) || s.Description.Contains(searchString)).ToList();
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View(AllTickets.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult EditTicket(int ticketId)
        {
            var ticket = ProjectManagerBusinessLayer.GetTicket(ticketId);

            ViewBag.TicketStatusList = ProjectManagerBusinessLayer.TicketStatuses();
            ViewBag.TicketPrioritiesList = ProjectManagerBusinessLayer.TicketPriorities();
            ViewBag.TicketTypeList = ProjectManagerBusinessLayer.TicketTypes();
            return View(ticket);
        }
        [HttpPost]
        public ActionResult EditTicket(int ticketId, string title, string description, int ticketStatusId, int ticketPrioritieId, int ticketTypeId)
        {
            var sendTicket = ProjectManagerBusinessLayer.GetTicket(ticketId);
            Ticket ticket = new Ticket()
            {
                Id = ticketId,
                Title = title,
                Description = description,
                TicketStatusId = ticketStatusId,
                TicketPrioritieId = ticketPrioritieId,
                TicketTypeId = ticketTypeId,
                Updated = DateTime.Now,
                Created = sendTicket.Created,
                ProjectId = sendTicket.ProjectId,
                OwnerId = sendTicket.OwnerId,
                AssignedToUserId = sendTicket.AssignedToUserId,
            };

            var result = ProjectManagerBusinessLayer.EditTicket(User.Identity.GetUserId(), ticket);

            ViewBag.TicketStatusList = ProjectManagerBusinessLayer.TicketStatuses();
            ViewBag.TicketPrioritiesList = ProjectManagerBusinessLayer.TicketPriorities();
            ViewBag.TicketTypeList = ProjectManagerBusinessLayer.TicketTypes();

            if (result)
                return RedirectToAction("GetAllTickets");
            else
                return RedirectToAction("Index");
        }

        public ActionResult AssignTicketToDeveloper(int ticketId)
        {
            ViewBag.DevelopersList = ProjectManagerBusinessLayer.GetAllUsers().Where(w => w.Roles.Any(a => a.RoleId == ProjectManagerBusinessLayer.GetRoleId("developer"))).ToList();
            ViewBag.ticketId = ticketId;
            return View();
        }

        [HttpPost]
        public ActionResult AssignTicketToDeveloper(int ticketId, string userId)
        {
            var result = ProjectManagerBusinessLayer.AssignToDeveloper(User.Identity.GetUserId(), ticketId, userId);

            ViewBag.DevelopersList = ProjectManagerBusinessLayer.GetAllUsers().Where(w => w.Roles.Any(a => a.RoleId == ProjectManagerBusinessLayer.GetRoleId("developer"))).ToList();
            ViewBag.ticketId = ticketId;
            if (result)
                return RedirectToAction("GetAllTickets");
            else
                return RedirectToAction("Index");
        }

        public ActionResult UnAssignTicket(int ticketId)
        {
            ProjectManagerBusinessLayer.UnAssignTicket(User.Identity.GetUserId(), ticketId);

            return RedirectToAction("GetAllTickets");
        }

        public ActionResult AddComment(int ticketId)
        {
            ViewBag.ticketId = ticketId;
            return View();
        }
        [HttpPost]
        public ActionResult AddComment(int ticketId, string commentText)
        {
            var result = ProjectManagerBusinessLayer.AddComments(User.Identity.GetUserId(), ticketId, commentText);

            if (result)
                return RedirectToAction("GetAllTickets");
            else
                return View(ticketId);
        }

        public ActionResult ShowAllComments(int ticketId)
        {
            return View(ProjectManagerBusinessLayer.AllComments(ticketId));
        }

        public ActionResult AddAttachment(int ticketId)
        {
            ViewBag.ticketId = ticketId;
            return View();
        }
        [HttpPost]
        public ActionResult AddAttachment(int ticketId, string fileUrl, string filePath, string description)
        {
            var result = ProjectManagerBusinessLayer.AddAttachment(User.Identity.GetUserId(), ticketId, fileUrl, filePath, description);

            if (result)
                return RedirectToAction("GetAllTickets");
            else
                return View(ticketId);
        }

        public ActionResult ViewAllAttachments(int ticketId)
        {
            return View(ProjectManagerBusinessLayer.ShowAllAttachments(ticketId));
        }

        public ActionResult TicketHistory(int ticketId)
        {
            return View(ProjectManagerBusinessLayer.FullHistory(ticketId));
        }
    }
}

Shadow/Views/ProjectManager/AddAttachment.cshtml
@{
    ViewBag.Title = "AddAttachment";
}

<h2>Add an Attachment</h2>

@using (Html.BeginForm())
{
    @Html.Hidden("ticketId", (int)ViewBag.ticketId)
    <h4>File URL: </h4> @Html.TextBox("fileUrl")
    <h4>File Path: </h4> @Html.TextBox("filePath")
    <h4>Description: </h4> @Html.TextArea("description")

    <input type="submit" value="Add Attchment" name="Add Attachment" />
}

Shadow/Views/ProjectManager/AllProjects.cshtml
    @{
        ViewBag.Title = "AllProjectsByUser";
    }

    <h2>All Projects</h2>

    @if (Model != null)
    {
        <ul>
            @foreach (var pro in Model)
            {
                <li>
                    @pro.Name
                </li>
            }
        </ul>
    }

Shadow/Views/ProjectManager/AllProjectsByUser.cshtml
@model List<Shadow.Models.Project>
@{
    ViewBag.Title = "AllProjectsByUser";
}

<h2>All Projects By User</h2>

@if (Model != null)
{
    <ul>
        @foreach (var pro in Model)
        {
            <li>
                @pro.Name
            </li>
        }
    </ul>
}

Shadow/Views/ProjectManager/AssignTicketToDeveloper.cshtml
@{
    ViewBag.Title = "AssignTicketToDeveloper";
}

<h2>Assign Ticket To Developer</h2>

@using (Html.BeginForm())
{
    @Html.Hidden("ticketId", (int)ViewBag.ticketId)
    <h4>Please select a user to assign this ticket to: </h4> @Html.DropDownList("userId", new SelectList(ViewBag.DevelopersList, "Id", "UserName", "Id"))

    <input type="submit" name="Add" value="Add"/>
}

Shadow/Views/ProjectManager/AssignToProject.cshtml
@{
    ViewBag.Title = "AssignToProject";
}

<h2>Assign User To a Project</h2>

@using (Html.BeginForm())
{
    <h4>Select User from the List :</h4> @Html.DropDownList("userId", new SelectList(ViewBag.UserList, "Id", "UserName", "Id"))
    <h4>Select Project from the List : </h4> @Html.DropDownList("projectId", new SelectList(ViewBag.ProjectList, "Id", "Name", "Id"))

    <input type="submit" name="Add" value="Add" />
}

Shadow/Views/ProjectManager/CreateAProject.cshtml
@{
    ViewBag.Title = "CreateAProject";
}

<h2>Create A Project</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="form-group">
            <div class="col-md-10">
                Project Name : @Html.TextBox("projectName")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Shadow/Views/ProjectManager/EditProject.cshtml
@model Shadow.Models.Project

@{
    ViewBag.Title = "EditProject";
}

<h2>EditProject</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Shadow/Views/ProjectManager/EditTicket.cshtml
@model Shadow.Models.Ticket
@{
    ViewBag.Title = "EditTicket";
}

<h2>Edit the Ticket</h2>

@using (Html.BeginForm())
{
    @Html.Hidden("ticketId", Model.Id)
    <h4>Enter a new Title: </h4> @Html.TextBox("title")
    <h4>Enter a new Description: </h4> @Html.TextArea("description")
    <h4>Select ticket Status:</h4> @Html.DropDownList("ticketStatusId", new SelectList(ViewBag.TicketStatusList, "Id", "Name", "Id"))
    <h4>Select ticket Priority: </h4> @Html.DropDownList("ticketPrioritieId", new SelectList(ViewBag.TicketPrioritiesList, "Id", "Name", "Id"))
    <h4>Select ticket Type: </h4> @Html.DropDownList("ticketTypeId", new SelectList(ViewBag.TicketTypeList, "Id", "Name", "Id"))

    <input type="submit" name="Update" value="Update" />
}

Shadow/Views/ProjectManager/GetAllTickets.cshtml
@model PagedList.IPagedList<Shadow.Models.Ticket>
@using PagedList.Mvc

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "GetAllTickets";
}

<h2>All Tickets</h2>

Order By: <p style="display:inline">@Html.ActionLink("Order by Ascending", "GetAllTickets", new { sortOrder = "OrderByAscending", currentFilter = ViewBag.CurrentFilter })</p> | <p style="display:inline">@Html.ActionLink("Order by Descending", "GetAllTickets", new { sortOrder = "OrderByDescending", currentFilter = ViewBag.CurrentFilter })</p>

@using (Html.BeginForm("GetAllTickets", "ProjectManager", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Updated)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Updated)
            </td>
            <td>
                @Html.ActionLink("Edit Ticket", "EditTicket", new { ticketId = item.Id }, null) |
                @if (item.AssignedToUserId != null)
                {
                    @Html.ActionLink("UnAssign Task", "UnAssignTicket", new { ticketId = item.Id }, null)
                }
                else
                {
                    @Html.ActionLink("Assign to Developer", "AssignTicketToDeveloper", new { ticketId = item.Id }, null)
                } |
                @Html.ActionLink("Add a Comment", "AddComment", new { ticketId = item.Id }, null)
                @if (item.TicketComments.Count != 0)
                {@Html.ActionLink("Show all comments", "ShowAllComments", new { ticketId = item.Id }, null)}
                | @Html.ActionLink("Add an Attachment", "AddAttachment", new { ticketId = item.Id }, null) | @if (item.TicketAttachements.Count != 0)
                {@Html.ActionLink("View all attachments", "ViewAllAttachments", new { ticketId = item.Id }, null)}

                @Html.ActionLink("Show Ticket History", "TicketHistory", new { ticketId = item.Id }, null)
            </td>
        </tr>
    }

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("GetAllTickets",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

Shadow/Views/ProjectManager/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Project Manager Dashboard</h2>
<div class="row">
    <div class="col-md-4">
        <h3 class="btn btn-default">
            @Html.ActionLink("Create a new project", "CreateAProject", "ProjectManager")
        </h3>
    </div>
    <div class="col-md-4">
        <h3 class="btn btn-default">
            @Html.ActionLink("View all my projects", "AllProjectsByUser", "ProjectManager")
        </h3>
    </div>
    <div class="col-md-4">
        <h3 class="btn btn-default">
            @Html.ActionLink("View all projects in the system", "AllProjects", "ProjectManager")
        </h3>
    </div>
    <div class="col-md-4">
        <h3 class="btn btn-default">
            @Html.ActionLink("Assign user to a project", "AssignToProject", "ProjectManager")
        </h3>
    </div>
    <div class="col-md-4">
        <h3 class="btn btn-default">
            @Html.ActionLink("UnAssign user from a project", "UnAssignFromProject", "ProjectManager")
        </h3>
    </div>
    <div class="col-ms-4">
        <h3 class="btn btn-default">
            @Html.ActionLink("Ticket Details", "GetAllTickets", "ProjectManager")
        </h3>
    </div>   
</div>

Shadow/Views/ProjectManager/ShowAllComments.cshtml
@model List<Shadow.Models.TicketComment>

@{
    ViewBag.Title = "ShowAllComments";
}

<h2>ShowAllComments</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Ticket.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().User.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Comment)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Created)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ticket.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comment)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Shadow/Views/ProjectManager/TicketHistory.cshtml
@model IEnumerable<Shadow.Models.TicketHistorie>

@{
    ViewBag.Title = "TicketHistory";
}

<h2>Ticket History</h2>

<p>Note: This list starts from top and add elemets at the end.</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ticket.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Property)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OldValue)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NewValue)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ticket.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Property)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OldValue)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NewValue)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Shadow/Views/ProjectManager/UnAssignFromProject.cshtml
@{
    ViewBag.Title = "UnAssignFromProject";
}

<h2>UnAssign User From a Project</h2>

@using (Html.BeginForm())
{
    <h4>Select User from the List :</h4> @Html.DropDownList("userId", new SelectList(ViewBag.UserList, "Id", "UserName", "Id"))
    <h4>Select Project from the List : </h4> @Html.DropDownList("projectId", new SelectList(ViewBag.ProjectList, "Id", "Name", "Id"))

    <input type="submit" name="Remove" value="Remove" />
}

Shadow/Views/ProjectManager/ViewAllAttachments.cshtml
@model List<Shadow.Models.TicketAttachement>

@{
    ViewBag.Title = "ViewAllAttachments";
}

<h2>View All Attachments</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Ticket.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().User.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().FilePath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().FileUrl)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ticket.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FilePath)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FileUrl)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>