Shadow/Controllers/DevelopersController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PagedList;
using Shadow.BL;
using Shadow.Models;

namespace Shadow.Controllers
{
    [Authorize(Roles = "developer")]
    public class DevelopersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        DeveloperBusinessLayer DeveloperBusinessLayer = new DeveloperBusinessLayer();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AllProject()
        {
            var projects = DeveloperBusinessLayer.AllProject(User.Identity.GetUserId());
            return View(projects);
        }
        public ActionResult GetAllTickets(string sortOrder, string currentFilter, string searchString, int? page)
        {
            List<Ticket> AllTickets;
            ViewBag.CurrentSort = sortOrder;

            if (sortOrder != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            switch (sortOrder)
            {
                case "OrderByAscending":
                    AllTickets = DeveloperBusinessLayer.GetAllTickets(User.Identity.GetUserId()).OrderBy(a => a.Title).ToList();
                    break;
                case "OrderByDescending":
                    AllTickets = DeveloperBusinessLayer.GetAllTickets(User.Identity.GetUserId()).OrderByDescending(d => d.Title).ToList();
                    break;
                default:
                    AllTickets = DeveloperBusinessLayer.GetAllTickets(User.Identity.GetUserId());
                    break;
            }

            if (!string.IsNullOrEmpty(searchString))
            {
                AllTickets = AllTickets.Where(s => s.Title.Contains(searchString) || s.Description.Contains(searchString)).ToList();
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View(AllTickets.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult GetAllTicketAssignToDeveloper(string sortOrder, string currentFilter, string searchString, int? page)
        {
            List<Ticket> AllTickets;
            ViewBag.CurrentSort = sortOrder;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            switch (sortOrder)
            {
                case "OrderByAscending":
                    AllTickets = DeveloperBusinessLayer.ticketsAssignToDeveloper(User.Identity.GetUserId()).OrderBy(a => a.Title).ToList();
                    break;
                case "OrderByDescending":
                    AllTickets = DeveloperBusinessLayer.ticketsAssignToDeveloper(User.Identity.GetUserId()).OrderByDescending(d => d.Title).ToList();
                    break;
                default:
                    AllTickets = DeveloperBusinessLayer.ticketsAssignToDeveloper(User.Identity.GetUserId());
                    break;
            }

            if (!string.IsNullOrEmpty(searchString))
            {
                AllTickets = AllTickets.Where(s => s.Title.Contains(searchString) || s.Description.Contains(searchString)).ToList();
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View(AllTickets.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult AddComment(int ticketId)
        {
            ViewBag.ticketId = ticketId;
            return View();
        }
        [HttpPost]
        public ActionResult AddComment(int ticketId, string commentText)
        {
            var result = DeveloperBusinessLayer.AddComments(User.Identity.GetUserId(), ticketId, commentText);

            if (result)
                return RedirectToAction("GetAllTickets");
            else
                return View(ticketId);
        }

        public ActionResult ShowAllComments(int ticketId)
        {
            return View(DeveloperBusinessLayer.AllComments(ticketId));
        }
        public ActionResult AddAttachment(int ticketId)
        {
            ViewBag.ticketId = ticketId;
            return View();
        }
        [HttpPost]
        public ActionResult AddAttachment(int ticketId, string fileUrl, string filePath, string description)
        {
            var result = DeveloperBusinessLayer.AddAttachment(User.Identity.GetUserId(), ticketId, fileUrl, filePath, description);

            if (result)
                return RedirectToAction("GetAllTickets");
            else
                return View(ticketId);
        }

        public ActionResult ViewAllAttachments(int ticketId)
        {
            return View(DeveloperBusinessLayer.ShowAllAttachments(ticketId));
        }
        public ActionResult TicketHistory(int ticketId)
        {
            return View(DeveloperBusinessLayer.FullHistory(ticketId));
        }
        public ActionResult AllNotification(int ticketId)
        {
            return View(DeveloperBusinessLayer.AllNotification(ticketId));
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

Shadow/Views/Developers/AddAttachment.cshtml
@{
    ViewBag.Title = "AddAttachment";
}

<h2>Add an Attachment</h2>

@using (Html.BeginForm())
{
    @Html.Hidden("ticketId", (int)ViewBag.ticketId)
    <h4>File URL: </h4> @Html.TextBox("fileUrl")
    <h4>File Path: </h4> @Html.TextBox("filePath")
    <h4>Description: </h4> @Html.TextArea("description")

    <input type="submit" value="Add Attchment" name="Add Attachment" />
}

Shadow/Views/Developers/AddComment.cshtml
@{
    ViewBag.Title = "AddComment";
}

<h2>AddComment</h2>
@using (Html.BeginForm())
{
    @Html.Hidden("ticketId", (int)ViewBag.ticketId)
    <h4>Enter comment here :</h4> @Html.TextArea("commentText")
    <input type="submit" value="Add" name="Add" />
}

Shadow/Views/Developers/AllNotification.cshtml
@model IEnumerable<Shadow.Models.TicketNotification>

@{
    ViewBag.Title = "AllNotification";
}

<h2>AllNotification</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ticket.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NotificationDescription)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ticket.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NotificationDescription)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Shadow/Views/Developers/AllProject.cshtml
@model List<Shadow.Models.Project>
@{
    ViewBag.Title = "AllProjectsByDeveloepr";
}

<h2>All Projects</h2>

@if (Model != null)
{
    <ul>
        @foreach (var pro in Model)
        {
            <li>
                @pro.Name
            </li>
        }
    </ul>
}

Shadow/Views/Developers/AllProjects.cshtml
@model List<Shadow.Models.Project>
@{
    ViewBag.Title = "AllProjectsByUser";
}

<h2>All Projects</h2>

@if (Model != null)
{
    <ul>
        @foreach (var pro in Model)
        {
            <li>
                @pro.Name
            </li>
        }
    </ul>
}

Shadow/Views/Developers/GetAllTicketAssignToDeveloper.cshtml
@model PagedList.IPagedList<Shadow.Models.Ticket>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "GetAllTicketAssignToDeveloper";
}

<h2>GetAllTicketAssignToDeveloper</h2>

Order By: <p style="display:inline">@Html.ActionLink("Order by Ascending", "GetAllTickets", new { sortOrder = "OrderByAscending", currentFilter = ViewBag.CurrentFilter })</p> | <p style="display:inline">@Html.ActionLink("Order by Descending", "GetAllTickets", new { sortOrder = "OrderByDescending", currentFilter = ViewBag.CurrentFilter })</p>

@using (Html.BeginForm("GetAllTickets", "develoepr", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().AssignedToUser.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Owner.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Project.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().TicketPrioritie.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().TicketStatus.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().TicketType.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Updated)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AssignedToUser.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Owner.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Project.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TicketPrioritie.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TicketStatus.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TicketType.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Updated)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Add a Comment", "AddComment", new { ticketId = item.Id }, null)
                @if (item.TicketComments.Count != 0)
                {@Html.ActionLink("Show all comments", "ShowAllComments", new { ticketId = item.Id }, null)}
            </td>
        </tr>
    }

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("GetAllTickets",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

Shadow/Views/Developers/GetAllTickets.cshtml
@model PagedList.IPagedList<Shadow.Models.Ticket>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "GetAllTickets";
}

<h2>GetAllTickets</h2>


Order By: <p style="display:inline">@Html.ActionLink("Order by Ascending", "GetAllTickets", new { sortOrder = "OrderByAscending", currentFilter = ViewBag.CurrentFilter })</p> | <p style="display:inline">@Html.ActionLink("Order by Descending", "GetAllTickets", new { sortOrder = "OrderByDescending", currentFilter = ViewBag.CurrentFilter })</p>

@using (Html.BeginForm("GetAllTickets","develoepr", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().AssignedToUser.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Owner.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Project.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().TicketPrioritie.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().TicketStatus.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().TicketType.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Updated)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AssignedToUser.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Owner.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Project.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TicketPrioritie.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TicketStatus.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TicketType.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Updated)
            </td>
            <td>
                @Html.ActionLink("Add a Comment", "AddComment", new { ticketId = item.Id }, null)
                @if (item.TicketComments.Count != 0)
                {@Html.ActionLink("Show all comments", "ShowAllComments", new { ticketId = item.Id }, null)}
            </td>
        </tr>
    }

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("GetAllTickets",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

Shadow/Views/Developers/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Developer Dashboard</h2>
<div class="row">
    <div class="col-md-4">
        <h3 class="btn btn-default">
            @Html.ActionLink("View Notification", "AllNotification", "Developers")
        </h3>
    </div>
    <div class="col=md-4">
        <h3 class="btn btn-default">
            @Html.ActionLink("View all projects in the system", "AllProjects", "Developers")
        </h3>
    </div>
    <div class="col-md-4">
        <h3 class="btn btn-default">
            @Html.ActionLink("Ticket Details", "GetAllTickets", "Developers")
        </h3>
    </div>
</div>

Shadow/Views/Developers/ShowAllComments.cshtml
@model IEnumerable<Shadow.Models.TicketComment>

@{
    ViewBag.Title = "ShowAllComments";
}

<h2>ShowAllComments</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ticket.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comment)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ticket.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comment)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Shadow/Views/Developers/TicketHistory.cshtml
@model IEnumerable<Shadow.Models.TicketHistorie>

@{
    ViewBag.Title = "TicketHistory";
}

<h2>Ticket History</h2>

<p>Note: This list starts from top and add elemets at the end.</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ticket.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Property)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OldValue)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NewValue)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ticket.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Property)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OldValue)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NewValue)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

Shadow/Views/Developers/ViewAllAttachments.cshtml
@model IEnumerable<Shadow.Models.TicketAttachement>

@{
    ViewBag.Title = "ViewAllAttachments";
}

<h2>ViewAllAttachments</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ticket.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FilePath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FileUrl)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ticket.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FilePath)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FileUrl)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>