Shadow/Controllers/SubmittersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PagedList;
using Shadow.BL;
using Shadow.DAL;
using Shadow.Models;

namespace Shadow.Controllers
{
    [Authorize(Roles ="submitter")]
    public class SubmittersController : Controller
    {
        SubmitterBusinessLayer SubmitterBusinessLayer = new SubmitterBusinessLayer();
        TicketRepository TicketRepository = new TicketRepository();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateTicket()
        {
            ViewBag.ProjectList = SubmitterBusinessLayer.ListProjects(User.Identity.GetUserId());
            ViewBag.TicketTypes = SubmitterBusinessLayer.TicketTypes();
            ViewBag.TicketPriorities = SubmitterBusinessLayer.AllTicketPriorities();
            ViewBag.TicketStatuses = SubmitterBusinessLayer.TicketStatuses();
            return View();
        }
        [HttpPost]
        public ActionResult CreateTicket(string title, int projectId, string description, int ticketTypeId, int ticketPrioritiesId, int ticketStatusId)
        {
            var userId = User.Identity.GetUserId();
            SubmitterBusinessLayer.CreateTicket(title, userId, projectId, description, ticketTypeId, ticketPrioritiesId, ticketStatusId);
            ViewBag.ProjectList = SubmitterBusinessLayer.ListProjects(User.Identity.GetUserId());
            ViewBag.TicketTypes = SubmitterBusinessLayer.TicketTypes();
            ViewBag.TicketPriorities = SubmitterBusinessLayer.AllTicketPriorities();
            ViewBag.TicketStatuses = SubmitterBusinessLayer.TicketStatuses();
            return View();
        }

        public ActionResult AllProjects()
        {
            var allProjects = SubmitterBusinessLayer.ListProjects(User.Identity.GetUserId());
            return View(allProjects);
        }

        public ActionResult GetAllTickets(string sortingOrder, string currentFilter, string searchString, int? page)
        {
            List<Ticket> Tickets;
            ViewBag.currentSort = sortingOrder;

            if(searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            switch (sortingOrder)
            {
                case "OrderByAscending":
                    Tickets = SubmitterBusinessLayer.GetAllTickets(User.Identity.GetUserId())
                        .OrderBy(t => t.Title).ToList();
                    break;
                case "OrderByDescending":
                    Tickets = SubmitterBusinessLayer.GetAllTickets(User.Identity.GetUserId())
                        .OrderByDescending(t => t.Title).ToList();
                    break;
                default:
                    Tickets = SubmitterBusinessLayer.GetAllTickets(User.Identity.GetUserId());
                    break;

            }
            if (!string.IsNullOrEmpty(searchString))
            {
                Tickets = Tickets.Where(s => s.Title.Contains(searchString) || s.Description.Contains(searchString)).ToList();
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View(Tickets.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult EditTicket(int ticketId)
        {
            var ticket = SubmitterBusinessLayer.GetTicket(ticketId);

            ViewBag.TicketStatusList = SubmitterBusinessLayer.TicketStatuses();
            ViewBag.TicketPrioritiesList = SubmitterBusinessLayer.AllTicketPriorities();
            ViewBag.TicketTypeList = SubmitterBusinessLayer.TicketTypes();
            return View(ticket);
        }
        [HttpPost]
        public ActionResult EditTicket(int ticketId, string title, string description, int ticketStatusId, int ticketPrioritieId, int ticketTypeId)
        {
            var sendTicket = SubmitterBusinessLayer.GetTicket(ticketId);
            Ticket ticket = new Ticket()
            {
                Id = ticketId,
                Title = title,
                Description = description,
                TicketStatusId = ticketStatusId,
                TicketPrioritieId = ticketPrioritieId,
                TicketTypeId = ticketTypeId,
                Updated = DateTime.Now,
                Created = sendTicket.Created,
                ProjectId = sendTicket.ProjectId,
                OwnerId = sendTicket.OwnerId,
                AssignedToUserId = sendTicket.AssignedToUserId,
            };

            var result = SubmitterBusinessLayer.EditTicket(User.Identity.GetUserId(), ticket);

            ViewBag.TicketStatusList = SubmitterBusinessLayer.TicketStatuses();
            ViewBag.TicketPrioritiesList = SubmitterBusinessLayer.AllTicketPriorities();
            ViewBag.TicketTypeList = SubmitterBusinessLayer.TicketTypes();

            if (result)
                return RedirectToAction("GetAllTickets");
            else
                return RedirectToAction("Index");
        }

        public ActionResult AddComment(int ticketId)
        {
            ViewBag.ticketId = ticketId;
            return View();
        }
        [HttpPost]
        public ActionResult AddComment(int ticketId, string commentText)
        {
            var result = SubmitterBusinessLayer.AddComments(User.Identity.GetUserId(), ticketId, commentText);

            if (result)
                return RedirectToAction("GetAllTickets");
            else
                return View(ticketId);
        }

        public ActionResult ShowAllComments(int ticketId)
        {
            return View(SubmitterBusinessLayer.AllComments(ticketId));
        }

        public ActionResult AddAttachment(int ticketId)
        {
            ViewBag.ticketId = ticketId;
            return View();
        }
        [HttpPost]
        public ActionResult AddAttachment(int ticketId, string fileUrl, string filePath, string description)
        {
            var result = SubmitterBusinessLayer.AddAttachment(User.Identity.GetUserId(), ticketId, fileUrl, filePath, description);

            if (result)
                return RedirectToAction("GetAllTickets");
            else
                return View(ticketId);
        }

        public ActionResult ViewAllAttachments(int ticketId)
        {
            return View(SubmitterBusinessLayer.ShowAllAttachments(ticketId));
        }

        public ActionResult TicketHistory(int ticketId)
        {
            return View(SubmitterBusinessLayer.FullHistory(ticketId));
        }
    }
}

Shadow/Views/Submitters/AddAttachment.cshtml
@{
    ViewBag.Title = "AddAttachment";
}

<h2>Add Attachment</h2>
@using (Html.BeginForm())
{
    @Html.Hidden("ticketId", (int)ViewBag.ticketId)
    <h4>File URL: </h4> @Html.TextBox("fileUrl")
    <h4>File Path: </h4> @Html.TextBox("filePath")
    <h4>Description: </h4> @Html.TextArea("description")

    <input type="submit" value="Add Attchment" name="Add Attachment" />
}

Shadow/Views/Submitters/AddComment.cshtml
@{
    ViewBag.Title = "AddComment";
}

<h2>Add a Comment</h2>

@using (Html.BeginForm())
{
    @Html.Hidden("ticketId", (int)ViewBag.ticketId)
    <h4>Enter comment here :</h4> @Html.TextArea("commentText")
    <input type="submit" value="Add" name="Add" />
}

Shadow/Views/Submitters/AllProjects.cshtml
@model List<Shadow.Models.Project>
@{
    ViewBag.Title = "AllProjects";
}

<h2>All Projects</h2>
@if (Model != null)
{
    <ul>
        @foreach (var pro in Model)
        {
            <li>
                @pro.Name
            </li>
        }
    </ul>
}

Shadow/Views/Submitters/CreateTicket.cshtml
@{
    ViewBag.Title = "CreateTicket";
}

<h2>Create Ticket</h2>

@using (Html.BeginForm())
{
    <h4>Please enter a ticket title: </h4> @Html.TextBox("title")
    <h4>Select project from the list: </h4> @Html.DropDownList("projectId", new SelectList(ViewBag.ProjectList, "Id", "Name", "Id"))
    <h4>Please enter description: </h4> @Html.TextArea("description")
    <h4>Please select ticket type: </h4> @Html.DropDownList("ticketTypeId", new SelectList(ViewBag.TicketTypes, "Id", "Name", "Id"))
    <h4>Please set Priority for the ticket : </h4> @Html.DropDownList("ticketPrioritiesId", new SelectList(ViewBag.TicketPriorities, "Id", "Name", "Id"))
    <h4>Please set Initial Ticket Status: </h4> @Html.DropDownList("ticketStatusId", new SelectList(ViewBag.TicketStatuses, "Id", "Name", "Id"))

    <input type="submit" value="Add" name="Add"/>
}

Shadow/Views/Submitters/EditTicket.cshtml
@model Shadow.Models.Ticket
@{
    ViewBag.Title = "EditTicket";
}

<h2>Edit Ticket</h2>

@using (Html.BeginForm())
{
    @Html.Hidden("ticketId", Model.Id)
    <h4>Enter a new Title: </h4> @Html.TextBoxFor(model => model.Title)
    <h4>Enter a new Description: </h4> @Html.TextArea("description")
    <h4>Select ticket Status:</h4> @Html.DropDownList("ticketStatusId", new SelectList(ViewBag.TicketStatusList, "Id", "Name", "Id"))
    <h4>Select ticket Priority: </h4> @Html.DropDownList("ticketPrioritieId", new SelectList(ViewBag.TicketPrioritiesList, "Id", "Name", "Id"))
    <h4>Select ticket Type: </h4> @Html.DropDownList("ticketTypeId", new SelectList(ViewBag.TicketTypeList, "Id", "Name", "Id"))

    <input type="submit" name="Update" value="Update" />
}

Shadow/Views/Submitters/GetAllTickets.cshtml
@model PagedList.IPagedList<Shadow.Models.Ticket>
@using PagedList.Mvc

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "GetAllTickets";
}

<h2>All Tickets</h2>

Order By: <p style="display:inline">@Html.ActionLink("Order by Ascending", "GetAllTickets", new { sortingOrder = "OrderByAscending", currentFilter = ViewBag.CurrentFilter })</p> |
<p style="display:inline">@Html.ActionLink("Order by Descending", "GetAllTickets", new { sortingOrder = "OrderByDescending", currentFilter = ViewBag.CurrentFilter })</p>

@using (Html.BeginForm("GetAllTickets", "Submitters", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Updated)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Updated)
            </td>
            <td>
                @Html.ActionLink("Edit Ticket", "EditTicket", new { ticketId = item.Id }, null) |
                @Html.ActionLink("Add a Comment", "AddComment", new { ticketId = item.Id }, null)
                @if (item.TicketComments.Count != 0)
                {@Html.ActionLink("Show all comments", "ShowAllComments", new { ticketId = item.Id }, null)}
                | @Html.ActionLink("Add an Attachment", "AddAttachment", new { ticketId = item.Id }, null) | @if (item.TicketAttachements.Count != 0)
                {@Html.ActionLink("View all attachments", "ViewAllAttachments", new { ticketId = item.Id }, null)} 

                @Html.ActionLink("Show Ticket History", "TicketHistory", new { ticketId = item.Id }, null)
            </td>
        </tr>
    }

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("GetAllTickets",
    new { page, sortingOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

Shadow/Views/Submitters/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Submitter Dashboard</h2>
<div class="row">
    <div class="col-md-4">
        <h3 class="btn btn-default">
            @Html.ActionLink("Create a new Ticket", "CreateTicket", "Submitters")
        </h3>
    </div>
    <div class="col-md-4">
        <h3 class="btn btn-default">
            @Html.ActionLink("View all projects in the system", "AllProjects", "Submitters")
        </h3>
    </div>
    <div class="col-md-4">
        <h3 class="btn btn-default">
            @Html.ActionLink("Ticket Details", "GetAllTickets", "Submitters")
        </h3>
    </div>
</div>

Shadow/Views/Submitters/ShowAllComments.cshtml
@model List<Shadow.Models.TicketComment>

@{
    ViewBag.Title = "ShowAllComments";
}

<h2>All Comments</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Ticket.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().User.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Comment)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Created)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ticket.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

Shadow/Views/Submitters/ViewAllAttachments.cshtml
@model List<Shadow.Models.TicketAttachement>

@{
    ViewBag.Title = "ViewAllAttachments";
}

<h2>View All Attachments</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Ticket.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().User.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().FilePath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().FileUrl)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ticket.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FilePath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FileUrl)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>